image: registry.gitlab.com/kitsudaiki/kitsunemimi-docker-files/ci_runner_unittest:1.0.0

build:
  script:
    - echo Working on branch $CI_COMMIT_REF_NAME

    - apt-get update
    - apt-get install -y libboost-filesystem-dev libssl-dev xxd

    - cd /builds/kitsudaiki/SakuraTree
    - ./build.sh test

    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:'/builds/kitsudaiki/result'

  tags:
    - docker
