image: registry.gitlab.com/tobiasanker/kitsunemimi-docker-files/ci_runner_unittest:1.0.0

build:
  script:
    - echo Working on branch $CI_COMMIT_REF_NAME

    - apt-get update
    - apt-get install -y libboost-filesystem-dev libboost-program-options-dev libsqlite3-dev

    - cd /builds/tobiasanker/SakuraTree
    - ./build.sh test

    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:'/builds/tobiasanker/result'
    - /builds/tobiasanker/result/SakuraTree

  tags:
    - docker
